# Supabase Configuration for SocialTouch MVP
# A global configuration file

project_id = "your-project-id"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://your-domain.com"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false
enable_recoveries = true
enable_phone_confirmations = false
enable_phone_change_with_password = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false
template = {}

[storage]
enabled = false

[edge_functions]
enabled = false

[analytics]
enabled = false