name = "socialtouch-license"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Cloudflare Pages configuration for standard Next.js
pages_build_output_dir = ".next"

[env.production]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.preview]
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables (add these via Cloudflare Dashboard)
# NEXT_PUBLIC_SUPABASE_URL
# NEXT_PUBLIC_SUPABASE_ANON_KEY
# SUPABASE_SERVICE_ROLE_KEY
# PAYPAL_CLIENT_ID
# PAYPAL_CLIENT_SECRET
# NEXT_PUBLIC_PAYPAL_PLAN_ID
# PAYPAL_WEBHOOK_ID
# PAYPAL_WEBHOOK_SECRET
# NEXT_PUBLIC_APP_URL